import React from 'react';

const TermsCo = () => {
    return (
        // Full page container with dark background
        <div className="min-h-screen bg-black text-white p-4 sm:p-8 md:p-12 lg:p-20">
            
            {/* Policy Container (Max width for readability) */}
            <div className="max-w-2xl mx-auto">
                
                {/* Main Title */}
                <h1 className="text-4xl font-bold text-center text-red-500 mb-8 pt-8  pb-4">
                    Terms & Conditions
                </h1>
                
                <div className="space-y-6 text-white text-justify ">
                    
                    {/* Section A */}
                    <p>
                        <span className="font-bold">A.</span> This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    </p>

                    {/* Section B */}
                    <p>
                        <span className="font-bold">B.</span> This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name **www.fusiongaming.in**, including the related mobile site and mobile application (hereinafter referred to as "Platform").
                    </p>

                    {/* Section C */}
                    <p>
                        <span className="font-bold">C.</span> The Platform is owned by Fusion Gaming, a company incorporated under the Companies Act, 1956 with its registered office at Marine Mall, Second Floor, Egattur, Chennai, Tamil Nadu - 600103. (hereinafter referred to as "Platform Owner", "we", "us", "our").
                    </p>

                    {/* Section D */}
                    <p>
                        <span className="font-bold">D.</span> Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with the Platform Owner. These Terms of Use relate to your use of our website, goods, services, or applications (collectively, "Services") as may be offered and contained on or provided by You which are in addition to or which contradict with these Terms of Use, are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
                    </p>

                    {/* Section E */}
                    <p>
                        <span className="font-bold">E.</span> For the purpose of these Terms of Use, wherever the context so requires "You", "your" or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
                    </p>

                    {/* Section F */}
                    <p>
                        <span className="font-bold">F.</span> Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and conditions under these terms of use, so please read the terms of use carefully before proceeding.
                    </p>

                    {/* Section G */}
                    <p>
                        <span className="font-bold">G.</span> The use of the Platform and/or availing of our services is subject to the following Terms of Use:
                    </p>

                    <ul className="list-disc list-inside space-y-2 ml-4">
                        <li>To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be solely liable for all acts done through the use of your registered account on the Platform.</li>
                        <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services, for any specific purpose.</li>
                        <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner.</li>
                        <li>The contents of the Platform and the Services are proprietary to us and are licensed to us.</li>
                        <li>You acknowledge that unauthorised use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</li>
                        <li>You agree to pay us the charges associated with availing the Services.</li>
                        <li>You agree not to use the Platform and/or Services for any purpose that is unlawful or forbidden by these Terms.</li>
                        <li>You agree and acknowledge that the website and the Services may contain links to other third-party websites.</li>
                        <li>You understand that upon initiating a transaction for availing the Services you are entering into a legally binding contract with the Platform Owner.</li>
                        <li>You shall indemnify and hold harmless Platform Owner and its affiliates from any claim or demand arising out of your breach of these terms.</li>
                        <li>In no event will the Platform Owner be liable for any indirect, consequential, incidental, special, or punitive damages.</li>
                        <li>The parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented by a force majeure event.</li>
                        <li>These Terms shall be governed by and construed in accordance with the laws of India.</li>
                        <li>All disputes shall be subject to the exclusive jurisdiction of the courts in Chennai, Tamil Nadu.</li>
                        <li>All concerns or communications relating to these Terms must be communicated to us using the email address <a href="mailto:www.fusiongaming.in" className="text-red-500 hover:underline font-semibold">www.fusiongaming.in</a>.</li>
                    </ul>

                </div>
            </div>
        </div>
    );
}

export default TermsCo;