import React from 'react';
import { MessageCircle, Phone, X, ArrowRight } from 'lucide-react'; 
const TermsCo = () => {
    return (
        // Full page container with dark background
        <div className="min-h-screen bg-black text-white px-3 py-4 sm:px-6 sm:py-8 md:px-12 md:py-12 lg:px-20 lg:py-20 font-inter">
            
            {/* Policy Container */}
            <div className="max-w-4xl mx-auto mt-16 sm:mt-8">
                
                {/* Main Title */}
                <h1 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-bold text-center text-red-600 mb-6 sm:mb-8 pt-4 sm:pt-8 pb-2 sm:pb-4 tracking-wide">
                    Terms & Conditions
                </h1>
                
                <div className="space-y-6 sm:space-y-8 text-gray-300 leading-relaxed font-light">
                    
                    {/* Section A */}
                    <section>
                        <h2 className="text-base sm:text-lg md:text-xl font-semibold text-red-500 mb-3 sm:mb-4 tracking-wide">Electronic Record</h2>
                        <p className="text-xs sm:text-sm md:text-base leading-relaxed text-gray-300">
                            <span className="font-medium text-white">A.</span> This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                        </p>
                    </section>

                    {/* Section B */}
                    <section>
                        <h2 className="text-base sm:text-lg md:text-xl font-semibold text-red-500 mb-3 sm:mb-4 tracking-wide">Publication Guidelines</h2>
                        <p className="text-xs sm:text-sm md:text-base leading-relaxed text-gray-300">
                            <span className="font-medium text-white">B.</span> This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name <span className="font-medium text-white">www.fusiongaming.in</span>, including the related mobile site and mobile application (hereinafter referred to as "Platform").
                        </p>
                    </section>

                    {/* Section C */}
                    <section>
                        <h2 className="text-base sm:text-lg md:text-xl font-semibold text-red-500 mb-3 sm:mb-4 tracking-wide">Platform Ownership</h2>
                        <p className="text-xs sm:text-sm md:text-base leading-relaxed text-gray-300">
                            <span className="font-medium text-white">C.</span> The Platform is owned by Fusion Gaming, a company incorporated under the Companies Act, 1956 with its registered office at Marine Mall, Second Floor, Egattur, Chennai, Tamil Nadu - 600103. (hereinafter referred to as "Platform Owner", "we", "us", "our").
                        </p>
                    </section>

                    {/* Section D */}
                    <section>
                        <h2 className="text-base sm:text-lg md:text-xl font-semibold text-red-500 mb-3 sm:mb-4 tracking-wide">Terms Governance</h2>
                        <p className="text-xs sm:text-sm md:text-base leading-relaxed text-gray-300">
                            <span className="font-medium text-white">D.</span> Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with the Platform Owner.
                        </p>
                    </section>

                    {/* Section E */}
                    <section>
                        <h2 className="text-base sm:text-lg md:text-xl font-semibold text-red-500 mb-3 sm:mb-4 tracking-wide">User Definition</h2>
                        <p className="text-xs sm:text-sm md:text-base leading-relaxed text-gray-300">
                            <span className="font-medium text-white">E.</span> For the purpose of these Terms of Use, wherever the context so requires "You", "your" or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
                        </p>
                    </section>

                    {/* Section F */}
                    <section>
                        <h2 className="text-base sm:text-lg md:text-xl font-semibold text-red-500 mb-3 sm:mb-4 tracking-wide">Agreement to Terms</h2>
                        <p className="text-xs sm:text-sm md:text-base leading-relaxed text-gray-300">
                            <span className="font-medium text-white">F.</span> Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and conditions under these terms of use, so please read the terms of use carefully before proceeding.
                        </p>
                    </section>

                    {/* Section G */}
                    <section>
                        <h2 className="text-base sm:text-lg md:text-xl font-semibold text-red-500 mb-3 sm:mb-4 tracking-wide">Terms of Service</h2>
                        <p className="text-xs sm:text-sm md:text-base leading-relaxed text-gray-300 mb-4">
                            <span className="font-medium text-white">G.</span> The use of the Platform and/or availing of our services is subject to the following Terms of Use:
                        </p>

                        <ul className="space-y-3 sm:space-y-4 text-xs sm:text-sm md:text-base leading-relaxed">
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be solely liable for all acts done through the use of your registered account on the Platform.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services, for any specific purpose.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">The contents of the Platform and the Services are proprietary to us and are licensed to us.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">You acknowledge that unauthorised use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">You agree to pay us the charges associated with availing the Services.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">You agree not to use the Platform and/or Services for any purpose that is unlawful or forbidden by these Terms.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">You agree and acknowledge that the website and the Services may contain links to other third-party websites.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">You understand that upon initiating a transaction for availing the Services you are entering into a legally binding contract with the Platform Owner.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">You shall indemnify and hold harmless Platform Owner and its affiliates from any claim or demand arising out of your breach of these terms.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">In no event will the Platform Owner be liable for any indirect, consequential, incidental, special, or punitive damages.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">The parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented by a force majeure event.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">These Terms shall be governed by and construed in accordance with the laws of India.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">All disputes shall be subject to the exclusive jurisdiction of the courts in Chennai, Tamil Nadu.</span>
                            </li>
                            <li className="pl-2 border-l-2 border-red-500/30">
                                <span className="text-gray-300">All concerns or communications relating to these Terms must be communicated to us using the email address <a href="mailto:www.fusiongaming.in" className="text-red-400 hover:text-red-300 underline transition-colors break-words">www.fusiongaming.in</a>.</span>
                            </li>
                        </ul>
                    </section>

                    {/* Contact Information */}
                    <section className="border-t border-gray-700 pt-6">
                        <h2 className="text-base sm:text-lg md:text-xl font-semibold text-red-500 mb-3 sm:mb-4 tracking-wide">Contact Us</h2>
                        <p className="text-xs sm:text-sm md:text-base leading-relaxed text-gray-300 mb-4">
                            For any questions regarding these Terms & Conditions, please contact us:
                        </p>
                        <div className="bg-gray-900/50 p-4 sm:p-6 rounded-lg border border-gray-800">
                            <div className="text-xs sm:text-sm md:text-base space-y-2 text-gray-300 leading-relaxed">
                                <p>Email: <a href="mailto:future.retail20@gmail.com" className="text-red-400 hover:text-red-300 underline transition-colors break-words">future.retail20@gmail.com</a></p>
                                <p>Phone: <a href="tel:+916369933507" className="text-red-400 hover:text-red-300 transition-colors">+91 63699 33507</a></p>
                                <p>Address: Marine Mall, Second Floor, Egattur, Chennai, Tamil Nadu - 600103</p>
                            </div>
                        </div>
                    </section>

                </div>
            </div>
            
            {/* Floating Action Buttons */}
            <div className="fixed right-3 sm:right-6 bottom-16 sm:bottom-20 z-50 flex flex-col space-y-3">
                <a href="https://wa.me/" 
                    className="bg-[#25D366] text-white p-2.5 sm:p-3 rounded-full shadow-lg hover:scale-105 transition-all duration-200 flex items-center justify-center">
                    <MessageCircle className="h-4 w-4 sm:h-5 sm:w-5 md:h-6 md:w-6" />
                </a>
                
                <a href="tel:" 
                    className="bg-blue-600 text-white p-2.5 sm:p-3 rounded-full shadow-lg hover:scale-105 transition-all duration-200 flex items-center justify-center">
                    <Phone className="h-4 w-4 sm:h-5 sm:w-5 md:h-6 md:w-6" />
                </a>
            </div>
        </div>
    );
}

export default TermsCo;